export const tokenFAQ = [
  {
    title: 'What are tokens?',
    content: 'Tokens can be thought of as pieces of words. Before prompts are processed, the input is broken down into chunks. These chunks are not cut up exactly where the words start or end - they can include trailing spaces and even sub-words. On average 1 token ~= 4 chars in English or ~= ¾ words.',
  },
  {
    title: 'How are tokens calculated?',
    content:
      'Tokens are calculated by the total number of chunks in the prompt and in the response. If a request is made with a prompt of 100 tokens and a response of 100 tokens, the total tokens used will be 200. Keep in mind requests regarding websites are pre-prompted with webpage data. All webpage data is refactored and minified to ensure the minimum amount of tokens are used whilst still providing the AI with the context it needs. The amount of tokens the webpage data will cost is highly variable depending on the website. A website with little content like www.google.com will only be around 100 tokens whilst a website with lots of content like a social media feed can be more than 2000 tokens. A simple way to check is to take note of your token count in your usage before and after a request. Generated prompts will also factor into your usage. See the "What are generated prompts?" section for more information. For more information you can check how many tokens are in a prompt using Open AI tokenizer: https://platform.openai.com/tokenizer.',
  },
  {
    title: 'How do I check how many tokens I have left?',
    content: 'Total tokens remaining and tokens used are displayed in the dashboard under "Usage".',
  },
  {
    title: 'What are generated prompts?',
    content: 'Generated prompts are prompts provided by the AI model to help you get started. These prompts are generated by the AI model and are not stored or retained by us. They are automatically generated when the extension is opened by prompting the AI model to provide helpful questions for you to ask about the webpage.',
  },
]

export const securityFAQ = [
  {
    title: 'Is my browser secure?',
    content: `Ensuring the security of your browser is a critical aspect of online safety. As a browser extension, our primary concern is the security and privacy of our users. We follow best practices to maintain a secure environment within the extension itself. We do not have access to any personal information you have not provided and only access websites at your request. It's important to note that browser security encompasses various factors beyond the extension. We recommend regularly updating your browser and using additional security measures like antivirus software to further enhance your browser's security.`,
  },
  {
    title: 'Do you store my messages?',
    content: `As a browser extension providing AI access, we prioritize user privacy and data protection. Any messages stored are completely anonymized and only used in an aggregated form to train and enhance the app. We do not store or retain any personal or identifiable information about the sender of any messages as all inputs provided to the extension are processed locally. We are committed to ensuring the confidentiality and privacy of our users' information.`,
  },
  {
    title: 'Does the AI model have access to my personal information?',
    content: 'No, the AI model used by the browser extension does not have the capability to access or retrieve personal data about individuals. Unless a user explicitly provides personal information directly to the AI model no personal data cam be accessed. We prioritize user privacy and ensure the confidentiality and security of your information.',
  },
  {
    title: 'Where can I find your full privacy policy?',
    content: 'Our full privacy policy can be found through the link at the bottom of this page or at https://www.versax.app/privacy-policy.',
  },
  {
    title: 'What AI model do you use?',
    content:
      "We utilize the GPT (Generative Pre-trained Transformer) AI model provided by OpenAI's API. GPT is a state-of-the-art language model that employs deep learning techniques to generate human-like text based on the given input. GPT has been trained on a vast amount of diverse text data to understand and generate coherent responses across various domains and topics. By leveraging OpenAI's API, our browser extension enables users to access the powerful capabilities of GPT and leverage its natural language processing capabilities for a wide range of tasks and applications.",
  },
  {
    title: 'How does does the AI model have access to a website?',
    content: 'When a request is made regarding a website, the request is pre-prompted with the data of the website the extension is running on. This allows the AI to understand the context of the request. All website data is refactored and minified to ensure the minimum amount of tokens are used whilst still providing the AI with the context it needs.',
  },
]
