export const PROMPT_DB = {
  promptOne: [
    { label: 'Summarise this page', ctxPrompt: 'Summarise the content of this page' },
    { label: 'Generate dot points of main content', ctxPrompt: 'Return a dot point list of main content in this page' },
    { label: 'Generate a brief description', ctxPrompt: 'Give a brief description of the content on this page' },
    { label: 'Generate summary of page', ctxPrompt: 'Create a summary of the content on this page' },
    { label: 'What can you tell me about this page?', ctxPrompt: 'What can you tell me about this page?' },
  ],
  promptTwo: [
    { label: 'Provide functional explanation', ctxPrompt: 'Provide functional explanation of this page' },
    { label: 'Provide comparative explanation', ctxPrompt: 'Provide comparative explanation of this page' },
    { label: 'Provide historical explanation', ctxPrompt: 'Provide historical explanation of this page' },
    { label: 'Provide benefits-oriented explanation', ctxPrompt: 'Provide benefits-oriented explanation of this page' },
    { label: 'Provide user-centric explanation', ctxPrompt: 'Provide user-centric explanation of this page' },
    { label: 'Provide step-by-step explanation', ctxPrompt: 'Provide step-by-step explanation of this page' },
    { label: 'Provide example-based explanation', ctxPrompt: 'Provide example-based explanation of this page' },
    { label: 'Provide metaphorical explanation', ctxPrompt: 'Provide metaphorical explanation of this page' },
  ],
  promptThree: [
    { label: 'Analyze the structure and layout', ctxPrompt: 'Analyze the structure and layout of this page' },
    { label: 'Identify keywords or phrases frequently mentioned', ctxPrompt: 'List and identify keywords or phrases frequently mentioned in this page' },
    { label: 'Extract any specific data or statistics mentioned', ctxPrompt: 'Extract any specific data or statistics mentioned in this page and list them' },
    { label: 'Suggest any related articles or resources', ctxPrompt: 'Suggest any related articles or resources for this page' },
    { label: 'Extract external sources or citations referenced', ctxPrompt: 'Extract external sources or citations referenced in this page' },
    { label: 'Tell me about the author', ctxPrompt: 'Tell me about the author of this page' },
    { label: 'What is the purpose of this page?', ctxPrompt: 'Describe the the purpose of this page?' },
    { label: 'Who is the target audience?', ctxPrompt: 'Who is the target audience of this page?' },
    { label: 'What are the main features or functionalities?', ctxPrompt: 'What are the main features or functionalities of this page?' },
    { label: 'How could this page be improved?', ctxPrompt: 'How could this page be improved, list examples?' },
    { label: 'What problems does this page solve?', ctxPrompt: 'What problems does this page aim solve?' },
  ],
  promptFour: [
    { label: 'Rewrite in style of New York Times article', ctxPrompt: 'Rewrite the page content in the style of a New York Times article' },
    { label: 'Rewrite as a childrens story', ctxPrompt: 'Rewrite the page content as a childrens story' },
    { label: 'Rewrite in style of a scientific paper', ctxPrompt: 'Rewrite the page content in the style of a scientific paper' },
    { label: 'Rewrite as a poem', ctxPrompt: 'Rewrite the page content as a poem' },
    { label: 'Rewrite as a song', ctxPrompt: 'Rewrite the page content as a song' },
    { label: 'Rewrite as a movie script', ctxPrompt: 'Rewrite the page content as a movie script' },
    { label: 'Rewrite as a novel', ctxPrompt: 'Rewrite the page content as a novel' },
    { label: 'Translate into french', ctxPrompt: 'Translate the page content into french' },
    { label: "Explain like I'm 5", prompt: "Explain the page content like I'm 5 years old" },
    { label: 'Explain with emojis', ctxPrompt: 'Explain the page content with emojis only' },
  ],
}
